# SPDX-FileCopyrightText: 2024 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  check-files:
    name: Check files
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v4
        with:
          # cache all intermediate layers in GHA cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # we don't care about pushing or loading the image though
          push: false
          load: false
